---
name: Build
on: push

jobs:
  build:
    strategy:
      matrix:
        version: [17]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '${{ matrix.version }}'
          distribution: 'adopt'
          cache: maven
      - name: Build without tests
        run: mvn --batch-mode -Dgpg.skip=true -Dmaven.test.skip=true clean package
      - name: Release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/hetznercloud-api*.jar